### ISSUE TITLE
不能全屏播放

### ISSUE THREAD

**Issue by 12366** [whitestarlau/ijkplayer4flutter#2]

**Comment by whitestarlau** [comment]
这个功能还没有加，demo里面的按钮只是在那里占位的。有时间我再完善。

**Comment by whitestarlau** [comment]
@12366 此功能已在demo中添加，目前切换的方式并不完美，比较生硬，隐藏其他控件也不方便，有更好的方式欢迎提出意见。另外需要指出的demo中的相关UI控件目前并非插件的核心功能，只是作为一个演示告诉使用者应当如何使用此插件，将来如果有需求的话会考虑移动这部分到lib中。
